// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoQDSbtgQPhyfT-_Y3va230KuT1ArcH10',
    appId: '1:768901766941:android:af77551e7dc12339c1cbf4',
    messagingSenderId: '768901766941',
    projectId: 'flutterpap-8a661',
    databaseURL: 'https://flutterpap-8a661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterpap-8a661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgFkn0x2Nt8tAEjI-Lk8wcUUhYfArOyk',
    appId: '1:768901766941:ios:908729ff2423d57cc1cbf4',
    messagingSenderId: '768901766941',
    projectId: 'flutterpap-8a661',
    databaseURL: 'https://flutterpap-8a661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterpap-8a661.appspot.com',
    iosClientId: '768901766941-qvcbvrpdgq6jjc9qgg84p8eg3ptt17p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pap',
  );
}
